/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2022-12-06 01:29:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/60c73f104d.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\" />\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>K LEAGUE DATA</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String userID = null;
	if (session.getAttribute("userID") != null) {
		userID = (String) session.getAttribute("userID");
	} else {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"top-bar\">\r\n");
      out.write("		<div class=\"top-bar__logo\">\r\n");
      out.write("			<a href=\"index.jsp\"> <img class=\"top-bar__logo__svg\"\r\n");
      out.write("				src=\"./css/img/logo.png\" alt=\"K리그 로고\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"top-bar__login\">\r\n");
      out.write("			<div class=\"top-bar__login__column\">\r\n");
      out.write("				");

				if (userID == null) {
				
      out.write("\r\n");
      out.write("				</span> <span class=\"top-bar__login__column__left\"> <a\r\n");
      out.write("					href=\"login.jsp\">로그인</a>\r\n");
      out.write("				</span>\r\n");
      out.write("\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<span class=\"top-bar__login__column__left\"> <a\r\n");
      out.write("					href=\"myInfo.jsp\">내정보</a> <span\r\n");
      out.write("					class=\"top-bar__login__column__right\"> <a\r\n");
      out.write("						href=\"logoutAction.jsp\">로그아웃</a> ");

 }
 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<header class=\"header-bar\">\r\n");
      out.write("		<div class=\"header-bar__team\">\r\n");
      out.write("			<a href=\"team.jsp\"> <span>팀</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-bar__player\">\r\n");
      out.write("			<a href=\"player.jsp\"> <span>선수</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-bar__calendar\">\r\n");
      out.write("			<a href=\"board.jsp\"> <span>게시판</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"info-bar\">\r\n");
      out.write("		<div class=\"info-bar__column\">\r\n");
      out.write("			<span>로그인 화면</span> <span>K리그의 로그인, 회원가입 할 수 있는 공간입니다.</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("		<div class=\"login\">\r\n");
      out.write("			<div class=\"container right-panel-active\">\r\n");
      out.write("				<!-- Sign Up -->\r\n");
      out.write("				<div class=\"container__form container--signup\">\r\n");
      out.write("					<form action=\"joinAction.jsp\" method=\"post\" class=\"form\">\r\n");
      out.write("						<h2 class=\"form__title\">회원가입</h2>\r\n");
      out.write("						<input type=\"text\" placeholder=\"ID\" class=\"input\" name=\"userID\" />\r\n");
      out.write("						<input type=\"password\" placeholder=\"Password\" class=\"input\"\r\n");
      out.write("							name=\"userPassword\" /> <input type=\"text\" placeholder=\"Name\"\r\n");
      out.write("							class=\"input\" name=\"userName\" /> <label class=\"form__label\"\r\n");
      out.write("							active> <input type=\"radio\" value=\"남자\" checked\r\n");
      out.write("							class=\"input\" name=\"userGender\" autocomplete=\"off\" />M <input\r\n");
      out.write("							type=\"radio\" value=\"여자\" class=\"input\" name=\"userGender\"\r\n");
      out.write("							autocomplete=\"off\" />W\r\n");
      out.write("						</label> <input type=\"text\" placeholder=\"Email\" class=\"input\"\r\n");
      out.write("							name=\"userEmail\" />\r\n");
      out.write("						<button class=\"btn\">회원가입</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Sign In -->\r\n");
      out.write("				<div class=\"container__form container--signin\">\r\n");
      out.write("					<form action=\"loginAction.jsp\" method=\"post\" class=\"form\">\r\n");
      out.write("						<h2 class=\"form__title\">로그인</h2>\r\n");
      out.write("						<input type=\"text\" placeholder=\"ID\" class=\"input\" name=\"userID\" />\r\n");
      out.write("						<input type=\"password\" placeholder=\"Password\" class=\"input\"\r\n");
      out.write("							name=\"userPassword\" /> <a href=\"#\" class=\"link\">비밀번호 찾기</a>\r\n");
      out.write("						<button class=\"btn\">로그인</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Overlay -->\r\n");
      out.write("				<div class=\"container__overlay\">\r\n");
      out.write("					<div class=\"overlay\">\r\n");
      out.write("						<div class=\"overlay__panel overlay--left\">\r\n");
      out.write("							<button class=\"btn\" id=\"signIn\">로그인</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"overlay__panel overlay--right\">\r\n");
      out.write("							<button class=\"btn\" id=\"signUp\">회원가입</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"./script/login-form.js\"></script>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"bottom-bar\">\r\n");
      out.write("		<a href=\"index.jsp\"> <img src=\"./css/img/foot_logo.png\"\r\n");
      out.write("			alt=\"K리그 투명로고\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
